### ISSUE TITLE
Krylov and preconditioners?

### ISSUE THREAD

**Issue by jedbrown** [luraess/julia-parallel-course-EGU21#1]
At a glance, it looks like you're showing stationary iterations, which is fine to demonstrate how to execute code, but not a good example of how to actually solve equations. I know y'all are aware aware of better solvers, but hope the pedagogy here can support best practices.

Depending on your perception of the audience, it'd be useful to have an exercise that compares accuracy vs cost to help navigate the thicket of confounding factors in scaling studies.

**Comment by luraess** [comment]
Thanks @jedbrown  for your insights and suggestions. We added an explicit "Disclaimer" notice warning the folks that many different solution approaches exists. Here, we focus on a modified stationary iteration scheme where "damping" is added to bring the convergence order closer to O(N) rather than O(N^2) - known and/or referred to as damped pseudo-transient approach (second order Richardson iterations in e.g. Frankel (1950)).

Due to short course  time limitations and expected broad and diverse background from the audience, we did not plan to dive further technical details.

I close this issue, but do not hesitate to follow up offline if you have specific suggestions or references.
